import { books } from "../Utils/Constant";

const SampleBook = ({ theme }) => {
  return (
    <section
      className="mt-[80px] text-center"
      aria-labelledby="sample-books-heading"
    >
      <h2
        id="sample-books-heading"
        className="mb-[20px] text-[1.5rem] font-bold"
      >
        Sample Books Generated by BookAI
      </h2>
      <p aria-describedby="sample-books-description">
        Explore some of the captivating books created using our AI technology.
      </p>
      <div className="flex justify-around flex-wrap max-md:flex-col">
        {books?.length > 0 ? (
          books.map((item, index) => (
            <div
              key={index}
              className={`basis-[calc(33.333%_-40px)] mb-[40px] mt-[80px] text-center ${
                theme === "dark"
                  ? "bg-[rgba(255,255,255,0.05)]"
                  : "bg-[rgba(94,90,155,0.5)]"
              } rounded-[10px] p-[10px] transition-all duration-300 ease-in-out hover:translate-y-[-10px]`}
              aria-labelledby={`book-title-${index}`}
              aria-describedby={`book-desc-${index}`}
            >
              <img
                src={item.bg}
                className="w-[12.5rem] h-[18.75rem] m-[0_auto_20px] flex justify-center items-center font-bold text-[1.125rem] text-center p-[10px] rounded-[10px]"
                alt={`Book cover for ${item.title}`}
              />
              <h3 id={`book-title-${index}`}>{item.title}</h3>
              <p
                id={`book-desc-${index}`}
                className={`italic ${
                  theme === "dark" ? "text-[#b3b3b3]" : "text-[#14141880]"
                } mb-[10px]`}
              >
                {item.desc}
              </p>
              <a
                href="#"
                className="inline-block mt-[10px] text-[#8a2be2] transition-all duration-300 ease-in-out hover:text-[#5e5a9b]"
                aria-label={`Read more about ${item.title}`}
              >
                Read More
              </a>
            </div>
          ))
        ) : (
          <p>No books available at the moment.</p>
        )}
      </div>
    </section>
  );
};

export default SampleBook;
